<template>
  <div class="p-6">
    <h1 class="text-2xl font-semibold text-gray-800 mb-6">System Reports</h1>
    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-for="report in reportTypes" :key="report.id" class="bg-white p-6 rounded shadow-sm border-t-4 border-[#3c8dbc]">
        <h3 class="font-bold text-gray-700 mb-2">{{ report.name }}</h3>
        <p class="text-sm text-gray-500 mb-4">{{ report.description }}</p>
        <button :disabled="generatingId === report.id" @click="generateReport(report)" class="text-[#3c8dbc] text-sm font-semibold hover:underline disabled:opacity-50">
          <i class="fa fa-download mr-1"></i> Generate Report
        </button>
      </div>
    </div>

    <div class="mt-8 bg-white rounded shadow-sm border overflow-hidden">
      <div class="px-4 py-3 border-b bg-gray-50 flex items-center justify-between">
        <h2 class="font-semibold text-gray-700">Generated Reports</h2>
        <button @click="loadHistory" class="text-xs px-3 py-1 border rounded hover:bg-gray-100">Refresh</button>
      </div>

      <table class="w-full text-left text-sm">
        <thead class="bg-gray-50 border-b text-[11px] uppercase text-gray-500 font-bold">
          <tr>
            <th class="p-3">Title</th>
            <th class="p-3">Category</th>
            <th class="p-3">Type</th>
            <th class="p-3">Generated By</th>
            <th class="p-3">Generated At</th>
            <th class="p-3 text-center">Action</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr v-for="item in history" :key="item.id">
            <td class="p-3">{{ item.title }}</td>
            <td class="p-3">{{ item.category }}</td>
            <td class="p-3">{{ item.type }}</td>
            <td class="p-3">{{ item.generated_by }}</td>
            <td class="p-3">{{ item.created_at }}</td>
            <td class="p-3 text-center">
              <button @click="downloadReport(item.id)" class="text-[#3c8dbc] font-semibold hover:underline">
                <i class="fa fa-download mr-1"></i> Download
              </button>
            </td>
          </tr>
          <tr v-if="!history.length">
            <td colspan="6" class="p-6 text-center text-gray-400">No reports generated yet.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import axios from 'axios'

const history = ref([])
const generatingId = ref(null)

const reportTypes = [
  { id: 1, name: 'Asset Inventory', category: 'inventory', description: 'Full list of all current assets and their statuses.' },
  { id: 2, name: 'Maintenance Summary', category: 'maintenance', description: 'Overview of repair costs and completion dates.' },
  { id: 3, name: 'User Assignments', category: 'assignments', description: 'List of assets currently assigned to people.' },
  { id: 4, name: 'Consumables', category: 'consumables', description: 'Stock levels and values for consumable items.' },
  { id: 5, name: 'Accessories', category: 'accessories', description: 'Accessory quantities, categories, and values.' },
  { id: 6, name: 'Components', category: 'components', description: 'Component inventory with serials and remaining quantities.' },
  { id: 7, name: 'Licenses', category: 'licenses', description: 'License seats, manufacturers, and pricing details.' },
  { id: 8, name: 'People', category: 'people', description: 'Users and roles for audit and access reporting.' },
  { id: 9, name: 'Activity Logs', category: 'activity logs', description: 'Audit trail of actions performed in the system.' },
]

const loadHistory = async () => {
  const { data } = await axios.get('/api/reports-history')
  history.value = data || []
}

const generateReport = async (report) => {
  try {
    generatingId.value = report.id
    await axios.post('/api/reports/generate', { category: report.category })
    await loadHistory()
    alert(`${report.name} generated successfully.`)
  } catch (e) {
    alert('Failed to generate report.')
  } finally {
    generatingId.value = null
  }
}

const downloadReport = async (id) => {
  try {
    const response = await axios.get(`/api/reports/${id}/download`, {
      responseType: 'blob',
      validateStatus: () => true,
    })

    if (response.status >= 400) {
      const text = await response.data.text()
      try {
        const parsed = JSON.parse(text)
        throw new Error(parsed.message || `Download failed (HTTP ${response.status})`)
      } catch {
        throw new Error(text || `Download failed (HTTP ${response.status})`)
      }
    }

    const disposition = response.headers['content-disposition'] || ''
    const match = disposition.match(/filename="?([^\"]+)"?/)
    const filename = match?.[1] || `report-${id}.csv`

    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', filename)
    document.body.appendChild(link)
    link.click()
    link.remove()
    window.URL.revokeObjectURL(url)
  } catch (e) {
    alert(e?.message || 'Failed to download report.')
  }
}

onMounted(loadHistory)
</script>